In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
print (a)

[1 2 3]


In [7]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [8]:
print (b.shape)

(2, 2)


In [10]:
c=np.reshape(1,4)

ValueError: cannot reshape array of size 1 into shape (4,)