In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
print (a)

[1 2 3]


In [6]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [7]:
print (b.shape)

(2, 2)


In [10]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x=np.arange(1,24,2,dtype=float)
x

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

#### Prg 1<br>
Write a numpy program to evaluate 2 list

In [23]:
l1=np.array([1,2,3,4])
l2=np.array([5,6,1,7])
gr=np.greater(l1,l2)
le=np.less_equal(l1,l2)
ge=np.greater_equal(l1,l2)
lt=np.less(l1,l2)
eq=np.equal(l1,l2)
print("L1 > L2: ",gr,"\nL1 <= L2",le,"\nL1 >= L2",ge,"\nL1 < L2",lt,"\nL1 = L2",eq)

In [25]:
print("L1 > L2: ",gr,"\nL1 <= L2",le,"\nL1 >= L2",ge,"\nL1 < L2",lt,"\nL1 = L2",eq)

L1 > L2:  [False False  True False] 
L1 <= L2 [ True  True False  True] 
L1 >= L2 [False False  True False] 
L1 < L2 [ True  True False  True] 
L1 = L2 [False False False False]


Without functions

In [31]:
l=[]
for (i,j) in zip(l1,l2):
    if i==j:
        l.append(True)
    else:
        l.append(False)

print("L1 = L2",l)

L1 = L2 [False, False, False, False]


#### Prg 2<br>
Write a numpy program to generate even number array from 50-90

In [2]:
l=np.arange(50,91,2)
print("Array: ",l)

Array:  [50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90]


#### Prg 3
create a numpy prgm to generate a 4x4 identity matrix

In [6]:
i=np.identity(4,dtype=int)
print("4x4 Identity Matrix")
print(i)

4x4 Identity Matrix
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### Prg4
generate 5x5 0 matrix with element on main diagonal 1,2,3,4,5

In [59]:
z=np.diag([1,2,3,4,5])
print(5x5 0 matrix with main diagonal 1,2,3,4,5)
print(z)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


write  a numoy prg to create a vector with values from 0 to 20 qnd change the sign of the numbers in the range from 9 to 15

In [7]:
import numpy as np
n=np.arange(0,21)
print("Original Vector", n)
for i in n:
    if i >=9 and i<=15:
        n[i]=i*-1
print("Vector after changing sign", n)


Original Vector [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Vector after changing sign [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


write a numoy prg to compute sum of all elements, sum of each col, adn sum of each row of givven array|

In [18]:
n=[[1,2],[5,3]]
a1=np.array(n)
print("Sum of all element:",a1.sum())
print("Sum of rows:",a1.sum(1))
print("Sum of col:",a1.sum(0))

sum od all element: 11
sum of rows: [3 8]
sum of col: [6 5]


write a nuumoy prg to save a given array to a text file and load it

In [25]:
n=np.arange(0,10)
with open("file.txt","w") as f:
    f.write(str(n))
with open("file.txt","r") as f:
    print(f.readlines())   

['[0 1 2 3 4 5 6 7 8 9]']


write a  numpy porg to check whether 2 arrays are equal, element wise comparison

In [27]:
n1=np.array([0,10])
n2=np.array([0,4])
a=np.equal(n1,n2)
print("Element-wise comparison",a)

[ True False]


write anumpy prg to create a 4x4 array with rand values, create  a  new array from the set array by swapping 1st and last rows

In [9]:
import random
l1=[]
for i in range(4):
    l2=[]
    for j in range(4):
        l2.append(random.randint(2,9))
    l1.append(l2)
m1=np.array(l1)
print("Original 4x4 matrix")
print(m1)
m1[[0,-1]]=m1[[-1,0]]
print("\nMatrix after swapping 1st and last row")
print(m1)
        

Original 4x4 matrix
[[8 8 3 5]
 [5 9 3 2]
 [9 6 4 8]
 [8 8 2 7]]

Matrix after swapping 1st and last row
[[8 8 2 7]
 [5 9 3 2]
 [9 6 4 8]
 [8 8 3 5]]


numpy prg tpo multiply 2 given arrays of same size element by element

In [11]:
n1=np.array([1,2,3,4,5])
n2=np.array([2,3,4,5,6])
print("Array 1: ",n1)
print("Array 2: ",n2)
print("Element wise product: ",n1*n2)

Array 1:  [1 2 3 4 5]
Array 2:  [2 3 4 5 6]
Element wise product:  [ 2  6 12 20 30]
