In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [5]:
print (a)

[1 2 3]


In [6]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [7]:
print (b.shape)

(2, 2)


In [10]:
s=np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x=np.arange(1,24,2,dtype=float)
x

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

#### Prg 1<br>
Write a numpy program to evaluate 2 list

In [23]:
l1=np.array([1,2,3,4])
l2=np.array([5,6,1,7])
gr=np.greater(l1,l2)
le=np.less_equal(l1,l2)
ge=np.greater_equal(l1,l2)
lt=np.less(l1,l2)
eq=np.equal(l1,l2)

In [25]:
print("L1 > L2: ",gr,"\nL1 <= L2",le,"\nL1 >= L2",ge,"\nL1 < L2",lt,"\nL1 = L2",eq)

L1 > L2:  [False False  True False] 
L1 <= L2 [ True  True False  True] 
L1 >= L2 [False False  True False] 
L1 < L2 [ True  True False  True] 
L1 = L2 [False False False False]


Without functions

In [31]:
l=[]
for (i,j) in zip(l1,l2):
    if i==j:
        l.append(True)
    else:
        l.append(False)

print("L1 = L2",l)

L1 = L2 [False, False, False, False]


#### Prg 2<br>
Write a numpy program to generate even number array from 50-90

In [33]:
l=np.arange(50,91,2)
l

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90])

#### Prg 3
create a numpy prgm to generate a 4x4 identity matrix

In [47]:
i=np.identity(2,dtype=int)
i

array([[1, 0],
       [0, 1]])

### Prg4
generate 5x5 0 matrix with element on main diagonal 1,2,3,4,5

In [59]:
z=np.diag([1,2,3,4,5])
print(z)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
