2x2 matrix using initialization<br>


In [2]:
import numpy  as np

In [7]:
import numpy  as np
m1=np.array([[1,2],[3,4]])
m2=np.array([[2,4],[6,8]])
print("Dot: \n",m1.dot(m2))
print("transpose: \n",np.transpose(m1))
print("inverse\n",np.linalg.inv(m1))
print("determinant\n",np.linalg.det(m1))
print("1D array\n",m1.flatten())



Dot: 
 [[14 20]
 [30 44]]
transpose: 
 [[1 3]
 [2 4]]
inverse
 [[-2.   1. ]
 [ 1.5 -0.5]]
determinant
 -2.0000000000000004
1D array
 [1 2 3 4]


matrix from user

In [9]:
matrix=[]
x=int(input("enter no of rows:"))
y=int(input("enter no of columns:"))
for i in range(x):
    row=[]
    for j in range(y):
        row.append(int(input()))
    matrix.append(row)
m1=np.array(matrix)
m1
print("transpose  \n" ,np.transpose(m1))

transpose  
 [[1 4]
 [2 5]
 [3 6]]


2nd way- user input matrix using list,map,split

In [15]:
matrix=[]
x=int(input("enter no of rows:"))
y=int(input("enter no of columns:"))
a=list(map(int,input().split()))
matrix.append(a)
m1=np.array(matrix)
m1=m1.reshape(x,y)
m1

array([[1, 2],
       [3, 4]])

<h1>Ex 2</h1>
<h5>Write a program to create 2 matrix from user and find the following
<ul><li>dot product</li>
<li>transpose</li>
<li>determinant</li>
<li>inverse</li>
<li>trace  .trace</li>
<li>rank matrix_rank</li>
<li>Eigen values and Eigeen vectors  eig</li></ul></h5>

In [17]:
matrix1=[]
matrix2=[]
r1,c1=list(map(int,input("enter no of rows nd col:").split()))
r2,c2=list(map(int,input("enter no of rows nd col:").split()))
a=list(map(int,input("enter nos").split()))
b=list(map(int,input("enter nos").split()))
matrix1.append(a)
matrix2.append(b)
m1=np.array(matrix1).reshape(r1,c1)
m2=np.array(matrix2).reshape(r2,c2)
dot=m2.dot(m1)
print(dot)
print("transpose:",np.transpose(m1))
print("determinant",np.linalg.det(m1))
print("inverse:",np.linalg.inv(m2))
print("trace",m1.trace())
print("rank",np.linalg.matrix_rank(m1))
print("eigen values",np.linalg.eig(m2))

[[13 20]
 [ 5  8]]
transpose: [[1 3]
 [2 4]]
determinant -2.0000000000000004
inverse: [[-0.5  1.5]
 [ 1.  -2. ]]
trace 5
rank 2
eigen values EigResult(eigenvalues=array([ 5.37228132, -0.37228132]), eigenvectors=array([[ 0.90937671, -0.56576746],
       [ 0.41597356,  0.82456484]]))


In [8]:
matrix1=[]
matrix2=[]
r1,c1=list(map(int,input("Enter no of rows and cols for matrix 1:").split()))
r2,c2=list(map(int,input("Enter no of rows and cols for matrix 2:").split()))
m=list(map(int,input("Enter elements of matrix 1:").split()))
matrix1.append(m)
m1=np.array(matrix1).reshape(r1,c1)
m=list(map(int,input("Enter elements of matrix 2:").split()))
matrix2.append(m)
m2=np.array(matrix2).reshape(r2,c2)
print("Matrix 1\n",m1)
print("\nMatrix 2\n",m1)
print("\nDot Product\n",np.dot(m1,m2))
print("\nTranspose of matrix 1\n",np.transpose(m1))
print("\nTranspose of matrix 2\n",np.transpose(m2))
print("\nInverse of matrix 1\n",np.linalg.inv(m1))
print("\nInverse of matrix 2\n",np.linalg.inv(m2))
print("\nDeterminant of matrix 1\n",np.linalg.det(m1))
print("\nDeterminant of matrix 2\n",np.linalg.det(m2))
print("\nTrace of matrix 1\n",m1.trace())
print("\nTrace of matrix 2\n",m2.trace())
print("\nRank of matrix 1\n",np.linalg.matrix_rank(m1))
print("\nRank of matrix 2\n",np.linalg.matrix_rank(m2))
print("\nEigen values and vectors of matrix 1\n",np.linalg.eig(m1))
print("\nEigne values and vectors of matrix 2\n",np.linalg.eig(m2))

Matrix 1
 [[1 2]
 [3 4]]

Matrix 2
 [[1 2]
 [3 4]]
Dot Product
 [[ 8  5]
 [20 13]]

Transpose of matrix 1
 [[1 3]
 [2 4]]

Transpose of matrix 2
 [[4 2]
 [3 1]]

Inverse of matrix 1
 [[-2.   1. ]
 [ 1.5 -0.5]]

Inverse of matrix 2
 [[-0.5  1.5]
 [ 1.  -2. ]]

Determinant of matrix 1
 -2.0000000000000004

Determinant of matrix 2
 -2.0

Trace of matrix 1
 5

Trace of matrix 2
 5

Rank of matrix 1
 2

Rank of matrix 2
 2

Eigen values and vectors of matrix 1
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

Eigne values and vectors of matrix 2
 EigResult(eigenvalues=array([ 5.37228132, -0.37228132]), eigenvectors=array([[ 0.90937671, -0.56576746],
       [ 0.41597356,  0.82456484]]))
