In [8]:
import numpy as np
a=list(map (int,input("enetr:").split()))
b=list(map( int,input("enter:").split()))
print(np.array([a,b]))

[[2 4]
 [3 5]]


In [20]:
np.array([2,3,4])
np.array([[1,2],[2,3]])
np.arange(2,10,2)
np.identity(3)
np.zeros(4,dtype=int).reshape(2,2)
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [25]:
s=np.arange(0,21,1)
for i in s:
    if i>=9 and i<=15:
        s[i]=-i
print(s)


[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [26]:
a=list(map(int,input("enter:").split()))
b=list(map(int,input("enter:").split()))
np.less(a,b)


array([ True,  True])

In [31]:
a=list(map(int,input("enter:").split()))
b=list(map(int,input("enetr:").split()))
s=np.array([a,b])
print(s)
s.sum(1)
s.sum(0)

[[3 4]
 [2 3]]


array([5, 7])

In [37]:
import random
l=[]
for i in range(16):
    l.append(random.randint(0, 10))
a=np.array(l).reshape(4,4)
print(a)
a[[0,-1]]=a[[-1,0]]
print(a)

[[ 2  0  5  1]
 [ 5 10  9  7]
 [ 3  8  8  5]
 [ 1  4  4  5]]
[[ 1  4  4  5]
 [ 5 10  9  7]
 [ 3  8  8  5]
 [ 2  0  5  1]]
